name: Deploy Service

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy .NET service over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e

            echo ">>> Go to service directory"
            cd /opt/kahvedostum-service

            echo ">>> Pull latest code"
            git pull

            echo ">>> Stop & remove old container"
            docker stop kahvedostum-service || true
            docker rm kahvedostum-service || true

            echo ">>> Remove old image"
            docker rmi kahvedostum-service || true

            echo ">>> Build new image"
            docker build -t kahvedostum-service .

            echo ">>> Run new container"
            docker run -d -p 5050:8080 --name kahvedostum-service kahvedostum-service

            echo ">>> Service deployment completed"
